### ISSUE TITLE
Upgrade documentation with better config file example

### ISSUE THREAD

**Issue by lpredova** [Rentlio/jit#1]
Hi,

It would be nice if there was better example of configuration file.

For instance, for me it was confusing what is my jira base url and project.

```
"url" : "YOUR JIRA BASE URL",
"project" : "OPTIONAL - JIRA PROJECT CODE"
```

In other examples there was url like this:
https://company.atlassian.net/rest/api/2/

But it was not intuitively enough that my link has to be in that specific format.

**Comment by ipadavic** [comment]
Readme is updated. New section Configuration options is added. Could you please check if this is ok and close issue if so.

**Comment by lpredova** [comment]
Gr8! Now is much better :tada:
